name: Country crate CI
on:
  pull_request:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format
      - run: cargo fmt
      - run: cargo fix --release --verbose
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
      - run: cargo build --release --verbose
    needs:
      - format
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
      - run: cargo test --release --verbose
    needs:
      - build
  dry_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to crates.io
      - run: cargo login ${{ secrets.COUNTRY_TOKEN }}
      - name: Dry publish
      - run: cargo publish --dry-run
    needs:
      - build
      - test
