name: Release country crate
on:
  push:
    tags:
      - 0*
env:
  CARGO_TERM_COLOR: always
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to crates.io
      - run: cargo login ${{ secrets.COUNTRY_TOKEN }}
      - name: Publish
      - run: cargo publish
